export default [
  "All",
  "CS Academic Office",
  "Central Academic Office",
  "Student Affairs Office",
  "Library",
  "IT & Network Office",
  "Disciplinary Committee",
  "Sports Office",
  "Transport",
  "Cafeteria",
  "Boarding House",
  "Engineering Labs",
  "FYP Committee",
  "Head Office",
  "Accounts",
  "One Stop",
  "HR",
  "School of Computing",
  "Islamabad Campus",
  "Flex",
];
